### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by scottdalgliesh** [scottdalgliesh/tally#1]
This issue tracks open items for implementing new features, updating existing functionality, and fixing bugs.

- [x] Filter options for review and summary pages.
- [ ] Fix broken test (tests/auth/routes.py: test_login)
- [ ] Add script to install Tika JAR on install, then use it instead of downloading a fresh JAR every time.
- [ ] Improve test data. Specifically, expand sample data to more accurately test summary views.
- [ ] Test using an in-memory database for testing to improve speed.
- [ ] Add summary information to home page (total count of bills uploaded, graph of monthly spending, top 3 categories, etc).
- [ ] Update database schema to change default category ONDELETE behavior of bills to "SET NULL".
- [ ] Add annual average to summarize page.
- [ ] Add data back-up (export/load) functionality.
- [ ] Add automatic periodic back-up of data.
- [ ] Make summary table collapsible (i.e. collapse year to single "average" row).
- [ ] Fix manual login vs redirected login discrepancy.
